<a href="https://colab.research.google.com/github/MELES-DS/DATA-SCIENCE-CODES/blob/main/updated_attenndance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import ipywidgets as widgets
from IPython.display import display, clear_output
import pandas as pd
import io
import os


# =====================================================
# GLOBAL STORAGE
# =====================================================

datasets = {}
dataset_months = {}
sorted_datasets = {}



# =====================================================
# MONTH ORDER
# =====================================================

month_order = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12
}



# =====================================================
# DETECT MONTH FROM DATASET COLUMN HEADERS
# Example:
# July 1, July 2, July 3 ... July 31
# =====================================================

def detect_month_from_dataset(df):

    month_count = {
        month: 0
        for month in month_order
    }


    # Check all column names

    for column in df.columns:

        column_name = str(column).strip().lower()


        for month in month_order:

            if month.lower() in column_name:

                month_count[month] += 1



    # Find month with highest repetition

    detected_month = max(
        month_count,
        key=month_count.get
    )


    if month_count[detected_month] > 0:

        return detected_month


    return "Unknown"





# =====================================================
# UPLOAD DATASET BUTTON
# =====================================================

upload = widgets.FileUpload(
    accept=".xlsx,.xls,.xlsm,.xlsb,.csv",
    multiple=True,
    description="📂 Upload Files"
)


display(upload)





# =====================================================
# LOAD DATASETS
# =====================================================

def load_file(change):

    global datasets
    global dataset_months
    global sorted_datasets


    datasets = {}
    dataset_months = {}
    sorted_datasets = {}



    for key, file_dict in upload.value.items():


        filename = file_dict["metadata"]["name"]


        extension = os.path.splitext(filename)[1].lower()


        file_data = io.BytesIO(
            file_dict["content"]
        )


        try:


            if extension == ".csv":

                df = pd.read_csv(file_data)



            elif extension in [
                ".xlsx",
                ".xls",
                ".xlsm",
                ".xlsb"
            ]:

                df = pd.read_excel(
                    file_data,
                    header=1
                )


            else:

                print(
                    "❌ Unsupported:",
                    filename
                )

                continue



            # Convert column names to lowercase

            df.columns = (
                df.columns
                .astype(str)
                .str.strip()
                .str.lower()
            )



            # Store dataset

            datasets[filename] = df



            # Detect month

            dataset_months[filename] = (
                detect_month_from_dataset(df)
            )



            print(
                "✅ Loaded:",
                filename,
                "| Month:",
                dataset_months[filename],
                "| Shape:",
                df.shape
            )



        except Exception as e:

            print(
                "❌ Error loading",
                filename,
                ":",
                e
            )



    # Sort datasets by calendar order

    sorted_datasets = dict(
        sorted(
            datasets.items(),
            key=lambda x:
            month_order.get(
                dataset_months[x[0]],
                99
            )
        )
    )


    print("\n📅 Chronological order:")


    for filename in sorted_datasets:

        print(
            dataset_months[filename],
            "→",
            filename
        )



upload.observe(
    load_file,
    names="value"
)





# =====================================================
# SELECT MONTH BUTTON
# =====================================================

select_month_button = widgets.Button(
    description="📅 Select Month",
    button_style="info"
)


display(select_month_button)





# =====================================================
# MONTH CHECKBOXES
# =====================================================

month_boxes = {}


month_box_container = widgets.VBox([])



for month in month_order:

    box = widgets.Checkbox(
        value=False,
        description=month
    )

    month_boxes[month] = box



month_box_container.children = list(
    month_boxes.values()
)



# Hide initially

month_box_container.layout.display = "none"


display(month_box_container)





# =====================================================
# DISPLAY DATASET BUTTON
# =====================================================

display_button = widgets.Button(
    description="▶ Display Dataset",
    button_style="success"
)


display(display_button)



output = widgets.Output()

display(output)





# =====================================================
# SHOW / HIDE MONTH CHECKBOXES
# =====================================================

def show_month_selector(button):

    if month_box_container.layout.display == "none":

        month_box_container.layout.display = "block"

        select_month_button.description = (
            "❌ Hide Month"
        )


    else:

        month_box_container.layout.display = "none"

        select_month_button.description = (
            "📅 Select Month"
        )



select_month_button.on_click(
    show_month_selector
)





# =====================================================
# DISPLAY DATASETS
# =====================================================

def display_selected(button):

    with output:

        clear_output()



        if not sorted_datasets:

            print(
                "⚠ Upload datasets first."
            )

            return



        selected_months = [

            month

            for month, box in month_boxes.items()

            if box.value

        ]



        print(
            "📅 Dataset display order:"
        )



        for filename, df in sorted_datasets.items():


            current_month = dataset_months[filename]



            # Filter if months selected

            if selected_months:

                if current_month not in selected_months:

                    continue



            print("=" * 80)

            print(
                "📅 Month:",
                current_month
            )

            print(
                "📂 File:",
                filename
            )

            print(
                "📊 Shape:",
                df.shape
            )

            print("=" * 80)



            display(
                df.head()
            )



display_button.on_click(
    display_selected
)

FileUpload(value={}, accept='.xlsx,.xls,.xlsm,.xlsb,.csv', description='📂 Upload Files', multiple=True)

Button(button_style='info', description='📅 Select Month', style=ButtonStyle())

VBox(children=(Checkbox(value=False, description='January'), Checkbox(value=False, description='February'), Ch…

Button(button_style='success', description='▶ Display Dataset', style=ButtonStyle())

Output()

✅ Loaded: DIY Attendance preparation  (1).xlsx | Month: July | Shape: (858, 36)
✅ Loaded: DIY Attendance preparation .xlsx | Month: July | Shape: (858, 36)

📅 Chronological order:
July → DIY Attendance preparation  (1).xlsx
July → DIY Attendance preparation .xlsx

In [91]:
import ipywidgets as widgets
from IPython.display import display, clear_output
import pandas as pd
import io
import os


# =====================================================
# GLOBAL STORAGE
# =====================================================

datasets = {}
dataset_months = {}
sorted_datasets = {}



# =====================================================
# MONTH ORDER
# =====================================================

month_order = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12
}



# =====================================================
# DETECT MONTH FROM COLUMN HEADERS
# Example:
# July 1, July 2, July 3 ...
# =====================================================

def detect_month_from_dataset(df):

    month_count = {
        month: 0
        for month in month_order
    }


    for column in df.columns:

        column_name = str(column).strip().lower()


        for month in month_order:

            if month.lower() in column_name:

                month_count[month] += 1



    detected_month = max(
        month_count,
        key=month_count.get
    )


    if month_count[detected_month] > 0:

        return detected_month


    return "Unknown"





# =====================================================
# UPLOAD DATASET
# =====================================================

upload = widgets.FileUpload(
    accept=".xlsx,.xls,.xlsm,.xlsb,.csv",
    multiple=True,
    description="📂 Upload Files"
)


display(upload)





# =====================================================
# LOAD FILES
# =====================================================

def load_file(change):

    global datasets
    global dataset_months
    global sorted_datasets


    datasets = {}
    dataset_months = {}
    sorted_datasets = {}



    for key, file_dict in upload.value.items():


        filename = file_dict["metadata"]["name"]


        extension = os.path.splitext(filename)[1].lower()


        file_data = io.BytesIO(
            file_dict["content"]
        )


        try:


            if extension == ".csv":

                df = pd.read_csv(file_data)



            elif extension in [
                ".xlsx",
                ".xls",
                ".xlsm",
                ".xlsb"
            ]:

                df = pd.read_excel(
                    file_data,
                    header=1
                )


            else:

                print(
                    "❌ Unsupported file:",
                    filename
                )

                continue



            # Lowercase column names

            df.columns = (
                df.columns
                .astype(str)
                .str.strip()
                .str.lower()
            )



            datasets[filename] = df



            dataset_months[filename] = (
                detect_month_from_dataset(df)
            )



            print(
                "✅ Loaded:",
                filename,
                "| Month:",
                dataset_months[filename],
                "| Shape:",
                df.shape
            )



        except Exception as e:

            print(
                "❌ Error loading",
                filename,
                ":",
                e
            )



    # Automatic chronological sorting

    sorted_datasets = dict(
        sorted(
            datasets.items(),
            key=lambda x:
            month_order.get(
                dataset_months[x[0]],
                99
            )
        )
    )



    print("\n📅 Automatic chronological order:")


    for filename in sorted_datasets:

        print(
            dataset_months[filename],
            "→",
            filename
        )



upload.observe(
    load_file,
    names="value"
)





# =====================================================
# SELECT MONTH BUTTON
# =====================================================

select_month_button = widgets.Button(
    description="📅 Select Month",
    button_style="info"
)


display(select_month_button)





# =====================================================
# MONTH CHECKBOXES
# =====================================================

month_boxes = {}


month_box_container = widgets.VBox([])



for month in month_order:

    box = widgets.Checkbox(
        value=False,
        description=month
    )

    month_boxes[month] = box



month_box_container.children = list(
    month_boxes.values()
)



month_box_container.layout.display = "none"


display(month_box_container)





# =====================================================
# DISPLAY DATASET BUTTON
# =====================================================

display_button = widgets.Button(
    description="▶ Display Dataset",
    button_style="success"
)


display(display_button)


output = widgets.Output()

display(output)





# =====================================================
# SHOW / HIDE MONTH CHECKBOX
# =====================================================

def show_month_selector(button):

    if month_box_container.layout.display == "none":

        month_box_container.layout.display = "block"

        select_month_button.description = (
            "❌ Hide Month"
        )


    else:

        month_box_container.layout.display = "none"

        select_month_button.description = (
            "📅 Select Month"
        )



select_month_button.on_click(
    show_month_selector
)





# =====================================================
# DISPLAY FUNCTION
# =====================================================

def display_selected(button):

    with output:

        clear_output()



        if not datasets:

            print(
                "⚠ Please upload dataset files first."
            )

            return



        # Selected months in checkbox order

        selected_months = [

            month

            for month, box in month_boxes.items()

            if box.value

        ]



        # -------------------------------------------------
        # No checkbox selected:
        # Use chronological order
        # -------------------------------------------------

        if not selected_months:

            display_order = sorted_datasets



        # -------------------------------------------------
        # Checkbox selected:
        # Use selected month order
        # -------------------------------------------------

        else:


            display_order = {}

            missing_months = []



            for selected_month in selected_months:


                found = False



                for filename, df in sorted_datasets.items():


                    if dataset_months[filename] == selected_month:


                        display_order[filename] = df

                        found = True

                        break



                if not found:

                    missing_months.append(
                        selected_month
                    )



            if missing_months:


                print(
                    "⚠ Select the correct month according to your uploaded file."
                )


                print(
                    "Missing:",
                    ", ".join(missing_months)
                )


                return





        # -------------------------------------------------
        # Display result
        # -------------------------------------------------

        print(
            "📅 Dataset display order:"
        )


        for filename, df in display_order.items():


            print("=" * 80)


            print(
                "📅 Month:",
                dataset_months[filename]
            )


            print(
                "📂 File:",
                filename
            )


            print(
                "📊 Shape:",
                df.shape
            )


            print("=" * 80)


            display(
                df.head()
            )



display_button.on_click(
    display_selected
)

FileUpload(value={}, accept='.xlsx,.xls,.xlsm,.xlsb,.csv', description='📂 Upload Files', multiple=True)

Button(button_style='info', description='📅 Select Month', style=ButtonStyle())

VBox(children=(Checkbox(value=False, description='January'), Checkbox(value=False, description='February'), Ch…

Button(button_style='success', description='▶ Display Dataset', style=ButtonStyle())

Output()

✅ Loaded: DIY Attendance preparation  (1).xlsx | Month: July | Shape: (858, 36)
✅ Loaded: DIY Attendance preparation .xlsx | Month: July | Shape: (858, 36)

📅 Automatic chronological order:
July → DIY Attendance preparation  (1).xlsx
July → DIY Attendance preparation .xlsx

In [70]:
print(datasets.keys())

dict_keys(['DIY Attendance preparation  (1).xlsx', 'DIY Attendance preparation .xlsx'])

In [74]:
print(f"✅ Loaded: {filename}")
print(f"📊 Shape: {df.shape}")

display(df.columns)

✅ Loaded: DIY Attendance preparation .xlsx
📊 Shape: (858, 36)

Index(['Column 1', 'Column 2', 'Name', 'Column2', 'DIY-ID', 'Sex', 'Age',
       'Column1', 'July 1', 'July 2', 'July 3', 'July 4', 'July 5', 'July 6',
       'July 7', 'July 8', 'July 9', 'July 10', 'July 13', 'July 14',
       'July 15', 'July 16', 'July 17', 'July 20', 'July 21', 'July 22',
       'July 23', 'July 24', 'July 27', 'July 28', 'July 29', 'July 30',
       'July 31', 'Column 31', 'Unnamed: 34', 'Unnamed: 35'],
      dtype='object')

In [90]:

for name, data in datasets.items():
    print(f"✅ Loaded: {filename}")
    print(f"📊 Shape: {df.shape}")
    print(name)
    display(data.head())
    print("\n \n \n")

✅ Loaded: DIY Attendance preparation .xlsx
📊 Shape: (858, 36)
DIY Attendance preparation  (1).xlsx

,column 1,column 2,name,column2,diy-id,sex,age,column1,july 1,july 2,...,july 23,july 24,july 27,july 28,july 29,july 30,july 31,column 31,unnamed: 34,unnamed: 35
0,NaN,1.0,Dawit Damtew,NaN,DIY 0699,M,16,NaN,📲🔲 Online Course,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0,CheckBox
1,NaN,2.0,Nahom Hayile,NaN,DIY 0722,M,17,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
2,NaN,3.0,Abayneh Gebeyaw,NaN,NaN,M,25,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,✔
3,NaN,4.0,Yohans Fasika,NaN,NaN,M,16,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,🌐 Internet
4,NaN,5.0,Eliyas Alemayehu,NaN,NaN,M,14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,🏛️📚 E - Library

✅ Loaded: DIY Attendance preparation .xlsx
📊 Shape: (858, 36)
DIY Attendance preparation .xlsx

,column 1,column 2,name,column2,diy-id,sex,age,column1,july 1,july 2,...,july 23,july 24,july 27,july 28,july 29,july 30,july 31,column 31,unnamed: 34,unnamed: 35
0,NaN,1.0,Dawit Damtew,NaN,DIY 0699,M,16,NaN,📲🔲 Online Course,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0,CheckBox
1,NaN,2.0,Nahom Hayile,NaN,DIY 0722,M,17,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
2,NaN,3.0,Abayneh Gebeyaw,NaN,NaN,M,25,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,✔
3,NaN,4.0,Yohans Fasika,NaN,NaN,M,16,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,🌐 Internet
4,NaN,5.0,Eliyas Alemayehu,NaN,NaN,M,14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,🏛️📚 E - Library